CREATE TABLE STG_MULTIPLAYER_BATTLE_STARTED
  (
    USER_ID                VARCHAR,
    EVENT_TIMESTAMP        TIMESTAMP_TZ,
    MULTIPLAYER_EVENT_ID   VARCHAR
  );
    
INSTERT INTO STG_LOGIN (USER_ID, EVENT_TIMESTAMP, LOGIN_EVENT_ID, USD_COST, USER_LTV)
    
SELECT 
    USER_ID, 
    EVENT_TIMESTAMP, 
    MULTIPLAYER_EVENT_ID
FROM SRC_MULTIPLAYER_BATTLE_STARTED