CREATE TABLE STG_IN_APP_PURCHASE_LOG_SERVER
  (
    USER_ID                VARCHAR,
    EVENT_TIMESTAMP        TIMESTAMP_TZ,
    IN_APP_PURCHASE_ID     VARCHAR,
    USD_COST               NUMBER,
     
  );

INSERT INTO STG_IN_APP_PURCHASE_LOG_SERVER (USER_ID, EVENT_TIMESTAMP, IN_APP_PURCHASE_ID, USD_COST)

SELECT 
    USER_ID, 
    EVENT_TIMESTAMP,
    IN_APP_PURCHASE_ID, 
    USD_COST
FROM SRC_IN_APP_PURCHASE_LOG_SERVER