CREATE TABLE STG_SESSION_STARTED (
    USER_ID                 VARCHAR NOT NULL,
    EVENT_TIMESTAMP         TIMESTAMP_TZ,
    SESSION_STARTED_ID      VARCHAR
);

INSERT INTO STG_SESSION_STARTED (USER_ID, EVENT_TIMESTAMP, SESSION_STARTED_ID)

SELECT 
        USER_ID, 
        EVENT_TIMESTAMP, 
        SESSION_STARTED_ID
FROM SRC_SESSION_STARTED