CREATE TABLE STG_SHIP_TRANSACTION_LOG (
    USER_ID                 VARCHAR NOT NULL,
    EVENT_TIMESTAMP         TIMESTAMP_TZ NOT NULL,
    SHIP_TRANSACTION_ID     VARCHAR,
    SHIP_ID                 VARCHAR,
    SC_AMOUNT               NUMBER,
    SHIP_TRANSACTION_STATUS VARCHAR
)

INSERT INTO STG_SHIP_TRANSACTION_LOG (USER_ID, EVENT_TIMESTAMP, SHIP_TRANSACTION_ID, SHIP_ID, SC_AMOUNT, SHIP_TRANSACTION_STATUS)

SELECT 
        USER_ID, 
        EVENT_TIMESTAMP, 
        SHIP_TRANSACTION_ID, 
        SHIP_ID, 
        SC_AMOUNT, 
        SHIP_TRANSACTION_STATUS,
FROM SRC_SHIP_TRANSACTION_LOG