CREATE TABLE STG_NEW_USER (
    USER_ID                 VARCHAR NOT NULL,
    EVENT_TIMESTAMP         TIMESTAMP WITH TIME ZONE,
    NEW_USER_EVENT_ID       VARCHAR,
);  
SELECT 
    USER_ID, 
    EVENT_TIMESTAMP, 
    NEW_USER_EVENT_ID, 
FROM SRC_NEW_USER