-- New users log
CREATE TABLE NEW_USER
  (
      BIRTH_YEAR                  TIMESTAMP_TZ,
      CAMPAIGN_INSTANCE           VARCHAR,
      COLLECT_INSERTED_TIMESTAMP  TIMESTAMP_TZ,
      EMAIL                       VARCHAR,
      EVENT_ID                    NUMBER,
      EVENT_TIMESTAMP             TIMESTAMP_TZ,
      EVENT_UUID                  VARCHAR,
      GENDER                      VARCHAR,
      MAIN_EVENT_ID               NUMBER,
      MS_SINCE_LAST_EVENT         DOUBLE,
      PLATFORM                    VARCHAR,
      SDK_VERSION                 VARCHAR,
      SESSION_ID                  VARCHAR,
      USER_COUNTRY                VARCHAR,
      USER_ID                     VARCHAR,
      USER_LEVEL                  NUMBER,
      USER_NAME                   VARCHAR,
      USER_SCORE                  NUMBER,
      USER_SERVER                 VARCHAR,
      USER_XP                     NUMBER,
      APPS_FLYER_ID               VARCHAR,
      USER_REGION                 VARCHAR,
      SERVER_VERSION              VARCHAR,
      USER_GEO                    VARCHAR,
      CLIENT_VERSION              VARCHAR,
      USER_CLAN_ID                VARCHAR,
      USER_TYPE                   VARCHAR,
      USER_CLAN_LEVEL             NUMBER,
      GDPR_PROCESSED_TS           TIMESTAMP_TZ,
      USER_INGAME_ID              VARCHAR,
      STORE                       VARCHAR
  );