-- Login tracking
CREATE TABLE LOGIN
  (
      EVENT_ID                      NUMBER,
      EVENT_TIMESTAMP               TIMESTAMP_TZ,
      EVENT_UUID                    VARCHAR,
      LOGIN_AUTHENTICATION_PLATFORM VARCHAR,
      LOGIN_SUCCESSFUL              BOOLEAN,
      MAIN_EVENT_ID                 NUMBER,
      MS_SINCE_LAST_EVENT           DOUBLE,
      PLATFORM                      VARCHAR,
      SDK_VERSION                   VARCHAR,
      SERVER_CLUSTER                VARCHAR,
      SESSION_ID                    VARCHAR,
      USER_ID                       VARCHAR,
      USER_IS_PREMIUM               BOOLEAN,
      USER_IS_SPENDER               BOOLEAN,
      USER_LEVEL                    NUMBER,
      USER_LTV                      NUMBER,
      USER_SCORE                    NUMBER,
      USER_SERVER                   VARCHAR,
      USER_XP                       NUMBER,
      ROW_NUMBER                    NUMBER,
      DEVICE_ID                     VARCHAR,
      LOGIN_ATTEMPT_ID              VARCHAR,
      USER_REGION                   VARCHAR,
      SERVER_VERSION                VARCHAR,
      CLIENT_VERSION                VARCHAR,
      USER_GEO                      VARCHAR,
      USER_TYPE                     VARCHAR,
      PLAYER_TYPE                   VARCHAR,
      USER_CLAN_ID                  VARCHAR,
      USER_INGAME_ID                VARCHAR,
      USER_CLAN_LEVEL               NUMBER,
      GDPR_PROCESSED_TS             TIMESTAMP_TZ,
      SC_BALANCE                    NUMBER,
      HC_BALANCE                    NUMBER,
      FREE_XP_BALANCE               NUMBER,
      LEAGUE_RATING_BALANCE         NUMBER,
      STORE                         VARCHAR,
  );