-- Ingame ship transations, where SC_AMOUNT < 0 == ship purchased by user, SC_AMOUNT >= 0 == ship sold by user
CREATE TABLE SHIP_TRANSACTION_LOG
  (
      COLLECT_INSERTED_TIMESTAMP  TIMESTAMP_TZ,
      EVENT_ID                    NUMBER,
      EVENT_TIMESTAMP             TIMESTAMP_TZ,
      EVENT_UUID                  VARCHAR,
      HC_AMOUNT                   NUMBER,
      MAIN_EVENT_ID               NUMBER,
      MS_SINCE_LAST_EVENT         DOUBLE,
      PLATFORM                    VARCHAR,
      SC_AMOUNT                   NUMBER,
      SDK_VERSION                 VARCHAR,
      SESSION_ID                  VARCHAR,
      SHIP_ID                     VARCHAR,
      SHIP_NAME                   VARCHAR,
      SHIP_NATION                 VARCHAR,
      SHIP_PREMIUM                BOOLEAN,
      SHIP_TIER                   NUMBER,
      SHIP_TYPE                   VARCHAR,
      TRANSACTION_ID              VARCHAR,
      USER_ID                     VARCHAR,
      USER_IS_PREMIUM             BOOLEAN,
      USER_IS_SPENDER             BOOLEAN,
      USER_LEVEL                  NUMBER,
      USER_LTV                    NUMBER,
      USER_SCORE                  NUMBER,
      USER_SERVER                 VARCHAR,
      USER_XP                     NUMBER,
      SERVER_VERSION              VARCHAR,
      USER_REGION                 VARCHAR,
      USER_TYPE                   VARCHAR,
      USER_GEO                    VARCHAR,
      PLAYER_TYPE                 VARCHAR,
      CLIENT_VERSION              VARCHAR,
      USER_CLAN_ID                VARCHAR,
      IN_APP_PURCHASE_ID          VARCHAR,
      REASON                      VARCHAR,
      REASON_EXTRA                VARCHAR,
      RANKED_COIN_AMOUNT          NUMBER,
      USER_INGAME_ID              VARCHAR,
      USER_CLAN_LEVEL             NUMBER,
      GDPR_PROCESSED_TS           TIMESTAMP_TZ,
      FREE_XP_AMOUNT              NUMBER,
      IS_FREE_GIFT                BOOLEAN,
      SHIP_LIMITED                NUMBER,
      STORE                       VARCHAR
  );