-- Store transactions
CREATE TABLE IN_APP_PURCHASE_LOG_SERVER
  (
      EVENT_TIMESTAMP        TIMESTAMP_TZ ,
      EVENT_UUID             VARCHAR,
      HC_PRODUCT_VALUE       NUMBER,
      HC_PRODUCT_VALUE_BONUS NUMBER,
      IN_APP_PURCHASE_ID     VARCHAR,
      IS_SANDBOX             BOOLEAN,
      PAYMENT_COUNTRY        VARCHAR,
      PLATFORM               VARCHAR,
      PLATFORM_PURCHASE_KEY  VARCHAR,
      PRODUCT_NAME           VARCHAR,
      REAL_CURRENCY_AMOUNT   NUMBER,
      REAL_CURRENCY_TYPE     VARCHAR,
      SESSION_ID             VARCHAR,
      USD_COST               NUMBER,
      USER_ID                VARCHAR,
      USER_IS_PREMIUM        BOOLEAN,
      USER_IS_SPENDER        BOOLEAN,
      USER_LEVEL             NUMBER,
      VALIDATED              BOOLEAN,
      USER_REGION            VARCHAR,
      SERVER_VERSION         VARCHAR,
      CLIENT_VERSION         VARCHAR,
      USER_GEO               VARCHAR,
      USER_TYPE              VARCHAR,
      USER_CLAN_ID           VARCHAR,
      FREE_XP_AMOUNT         NUMBER,
      SILVER_AMOUNT          NUMBER,
      GOLD_AMOUNT            NUMBER,
      PRE_SET_ITEM_ID        VARCHAR,
      IAP_ID                 VARCHAR,
      ITEM_IDS               VARCHAR,
      ALIAS                  VARCHAR,
      USER_INGAME_ID         VARCHAR,
      EVENT_ID               VARCHAR,
      USER_CLAN_LEVEL        NUMBER,
      IS_FREETRIAL           VARCHAR,
      STORE                  VARCHAR);